title = "Onur Yildiz"

[author]
  name = "Onur Yildiz"
  image = "img/onuryildiz.jpg"
  headline = "Full time SFU engineering student"
  bio = "Connect with me"
  links = [
    { email = "mailto:onur07132@gmail.com" },
    # { lastfm = "https://www.last.fm/user/onur_pro" },
    { linkedin = "https://www.linkedin.com/in/onur-yildiz-493a38230/" },
    { instagram = "https://www.instagram.com/theonuryildiz/" },
   ]
